{ config, pkgs, lib, unstable, ... }:

let
  dotfiles = "/etc/nixos/dotfiles";
  mkLink = path: config.lib.file.mkOutOfStoreSymlink path;
in
{
  home.username = "durian";
  home.homeDirectory = "/home/durian";
  home.stateVersion = "25.11";

  programs.home-manager.enable = true;
  
  # Enabling and configuration of Zsh 
  programs.zsh = {
      enable = true;
      enableCompletion = true;
      autosuggestion.enable = true;
      initContent = ''
        # Fastfetch at start
        fastfetch

        # Kali-like prompt
        PROMPT='%F{blue}┌──(%F{white}%n㉿%m%F{blue})-[%F{white}%~%F{blue}]
        %F{blue}└─%F{blue}$%f '
      '';
      oh-my-zsh = {
        enable = true;
        plugins = [
          "git"
          "python"
          "node"
          "man"
        ];
      };
      shellAliases = {
        # Navigation aliases 
        ls = "lsd";
	
	# File editing aliases
	snano = "sudo nano";

        # OS maintenance 
        rebuild-config = "cd /etc/nixos && sudo nixos-rebuild switch --flake .#WAV && cd ~";
        test-config = "cd /etc/nixos && sudo nixos-rebuild test --flake .#WAV && cd ~";
        clean = "sudo nix-collect-garbage -d";
        nix-list = "sudo nix-env --list-generations --profile /nix/var/nix/profiles/system";
        nix-config = "sudo nano /etc/nixos/configuration.nix";
        upd = "cd /etc/nixos && sudo nix-channel --update && sudo nixos-rebuild switch --upgrade --flake .#WAV && cd ~";
        del-old-gen = "sudo nix-env --delete-generations old -p /nix/var/nix/profiles/system";
	ipa = "ip -br -c -4 a";
	clr = "cat /dev/null > ~/.zsh_history && history -c";
      };
    };

  fonts.fontconfig.enable = true;

  home.packages =
    (with pkgs; [
      kdePackages.kate
      kdePackages.discover
      git
      btop
      vesktop
      ani-cli
      manga-tui
      protonvpn-gui
      cider-2
      steam
      localsend
      vscodium
      obsidian
      yubioath-flutter
      nixfmt-rfc-style
      remmina
      blender
      cava
      hyprland
      oh-my-zsh
      jetbrains.idea
      jetbrains.jdk
      jetbrains.pycharm
      kicad      
    ])
    ++
    (with unstable; [
      sbb-tui
    ]);

  xdg.configFile = {
    "fastfetch/nix.jsonc".source = mkLink "${dotfiles}/fastfetch/nix.jsonc";
    "hypr/hyprland.conf".source = mkLink "${dotfiles}/hypr/hyprland.conf";
  };

  # Install firefox.
  programs.firefox.enable = true;

  # Enable KDE Connect
  services.kdeconnect.enable = true;
  services.kdeconnect.indicator = true;

  programs.kitty = {
    enable = true;
    settings = {
      ## name: Sakura Night
      ## license: MIT
      ## author: PandaCatPlayz
      ## upstream: https://pandacatplayz.github.io/kitty-themes/Sakura_Night.conf
      ## blurb: A custom kitty dark theme loosely using the Endesga 32 palette

      background = "#181425";
      foreground = "#F06292";
      cursor = "#F06292";
      selection_background = "#F06292";

      #: black
      color0 = "#181425";
      color8 = "#262b44";

      #: red
      color1 = "#e43b44";
      color9 = "#ff0044";

      #: green
      color2 = "#3e8948";
      color10 = "#63c74d";

      #: yellow
      color3 = "#feae34";
      color11 = "#fee761";

      #: blue
      color4 = "#124e89";
      color12 = "#0099db";

      #: magenta
      color5 = "#b55088";
      color13 = "#F06292";

      #: cyan
      color6 = "#008080";
      color14 = "#66b2b2";

      #: white
      color7 = "#c0cbdc";
      color15 = "#ffffff";
      selection_foreground = "#f7f7f7";

      # START_AUTOGENERATED_TAB_STYLE
      # Feel free to update these colors manually and remove these comments.
      active_tab_foreground = "#eeeeee";
      active_tab_background = "#F06292";
      inactive_tab_foreground = "#F06292";
    };
  };

  programs.git = {
    enable = true;
    settings.user = {
      name = "Durian";
      email = "dorian@luyet.ch";
    };
    settings = {
      init.defaultBranch = "main";
      safe.directory = "/etc/nixos";
    };
  };

  home.file.".config/fastfetch/image/cirno.png".source = mkLink "${dotfiles}/fastfetch/image/cirno.png";
  home.file.".local/share/wallpapers/cyrene.jpg".source = mkLink "${dotfiles}/wallpapers/cyrene.jpg";
  home.file.".local/share/wallpapers/evernight.jpg".source = mkLink "${dotfiles}/wallpapers/evernight,jpg";
  home.file.".local/share/wallpapers/miku-samurai.jpg".source = mkLink "${dotfiles}/wallpapers/miku-samurai.jpg";
  home.file.".config/fastfetch/image/cirno2.png".source = mkLink "${dotfiles}/fastfetch/image/cirno2.png";
  home.file.".local/share/fastfetch/presets/nix.jsonc".source = mkLink "${dotfiles}/fastfetch/nix.jsonc";
  home.file.".local/share/wallpapers/nix_side.jpg".source = mkLink "${dotfiles}/wallpapers/nix_side.jpg";
  home.file.".local/share/wallpapers/nix_ascii.jpg".source = mkLink "${dotfiles}/wallpapers/nix_ascii.jpg";
  home.file.".local/share/wallpapers/nix_waves.jpg".source = mkLink "${dotfiles}/wallpapers/nix_waves.jpg";
}
